# Generated by Django 4.1 on 2022-08-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monsterspotting',
            old_name='monster_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='monsterspotting',
            old_name='monster_time',
            new_name='time',
        ),
    ]
